spring:
  profiles:
    active: dev
--- 
spring:
  profiles: dev
  application:
    name: springcloud-config-ictehi-dev
---
spring:
  profiles: text
  application:
    name: springcloud-config-ictehi-text