spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-client-3355
server:
  port: 8001
---
spring:
  profiles: text
  application:
    name: microservicecloud-config-client-3355
server:
  port: 8002
